### ISSUE TITLE
html file size is very large

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-actions/cohort-report#50]
500mb in my case which includes a couple of dozen fields or so. Presumably the images are much more detailed than required, especially if this isn't usually going to be released. 

Also, the images aren't visible in IE (default browser in backend) but are in Chrome (though they load very slowly!)

**Comment by iaindillingham** [comment]
Thanks for reporting this, @HelenCEBM. I think the issue is caused by Plotly, which writes each chart to the HTML file as a large amount of JavaScript/HTML. In #46, I replace Plotly with Matplotlib and write each chart as a PNG. This will give a smaller HTML file and, hopefully, a smaller collection of files overall.

See also:

* #40 
* #7

**Comment by iaindillingham** [comment]
For some evidence of my hand-waving, see: https://github.com/opensafely-actions/cohort-report/pull/46#issuecomment-959770077.
